[package]
name = "sg1"
version = "0.19.0"
edition = "2021"

authors = ["Shane Vitarana <s@noreply.publicawesome.com>"]
description = "Definition and types for the SG1 interface"
license = "Apache-2.0"
repository = "https://github.com/public-awesome/launchpad"
homepage = "https://stargaze.zone"

[dependencies]
cosmwasm-std = { version = "1.1.4" }
cw-utils = "0.15.0"
serde = { version = "1.0.133", default-features = false, features = ["derive"] }
sg-std = "0.19.0"
thiserror = "1.0.30"
