[package]
name = "sg-utils"
version = "0.1.0"
edition = "2021"
authors = ["Shane Vitarana <s@noreply.com>"]
description = "Common utilities for Stargaze contract"
license = "Apache-2.0"
repository = "https://github.com/public-awesome/contracts"
homepage = "https://stargaze.zone"

[dependencies]
bech32 = "0.8.1"
cosmwasm-std = "0.16.3"
