[package]
name = "sg2"
version = "0.2.0"
edition = "2021"
authors = ["Shane Vitarana <s@noreply.publicawesome.com>"]
description = "Definition and types for the SG2 interface"
license = "Apache-2.0"
repository = "https://github.com/public-awesome/launchpad"
homepage = "https://stargaze.zone"

[dependencies]
cosmwasm-std = { version = "1.0.0" }
cw-utils = "0.15.0"
serde = { version = "1.0.133", default-features = false, features = ["derive"] }
thiserror = "1.0.30"
schemars = "0.8.8"
sg721 = { path = "../sg721" }
