[package]
name = "sg-std"
version = "0.19.0"
edition = "2021"

authors = ["Jorge Hernandez <jorge@publicawesome.com>"]
description = "Bindings for CosmWasm contracts to call into custom modules of Stargaze"
license = "Apache-2.0"
repository = "https://github.com/public-awesome/launchpad"
homepage = "https://stargaze.zone"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cosmwasm-std = { version = "1.1.4" }
cw-utils = "0.15.0"
cw721 = "0.15.0"
schemars = "0.8.8"
serde = { version = "1.0.133", default-features = false, features = ["derive"] }
thiserror = "1.0.30"
cosmwasm-schema = { version = "1.1.4" }
