[package]
name = "sg-multi-test"
version = "0.16.0"
edition = "2021"
authors = ["Jorge Hernandez <jorge@publicawesome.com>"]
description = "Integration test helpers for Stargaze custom contracts"
license = "Apache-2.0"
repository = "https://github.com/public-awesome/launchpad"
homepage = "https://stargaze.zone"

[dependencies]
anyhow = "1"
cw-multi-test = "0.13.4"
cosmwasm-std = { version = "1.0.0" }
schemars = "0.8"
serde = { version = "1.0", default-features = false, features = ["derive"] }
sg-std = { path = "../sg-std" }
